/*
 * Trade API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: current
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Org.OpenAPITools.Client;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IIntradayCandlesApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Returns the list of intraday candles.  Возвращает внутридневные свечи.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="securityBoard">Trading Board.  Режим торгов. (optional)</param>
        /// <param name="securityCode">Security Code.  Тикер инструмента. (optional)</param>
        /// <param name="timeFrame">Timeframe.  Временной интервал. (optional)</param>
        /// <param name="intervalFrom">Date from.  Дата начала. (optional)</param>
        /// <param name="intervalTo">Date to.  Дата окончания. (optional)</param>
        /// <param name="intervalCount">Candles count limit.  Количество свечей. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetIntradayCandlesResultWebResponse</returns>
        GetIntradayCandlesResultWebResponse PublicApiV1IntradayCandlesGet(string? securityBoard = default(string?), string? securityCode = default(string?), string? timeFrame = default(string?), DateOnly? intervalFrom = default(DateOnly?), DateOnly? intervalTo = default(DateOnly?), int? intervalCount = default(int?), int operationIndex = 0);

        /// <summary>
        /// Returns the list of intraday candles.  Возвращает внутридневные свечи.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="securityBoard">Trading Board.  Режим торгов. (optional)</param>
        /// <param name="securityCode">Security Code.  Тикер инструмента. (optional)</param>
        /// <param name="timeFrame">Timeframe.  Временной интервал. (optional)</param>
        /// <param name="intervalFrom">Date from.  Дата начала. (optional)</param>
        /// <param name="intervalTo">Date to.  Дата окончания. (optional)</param>
        /// <param name="intervalCount">Candles count limit.  Количество свечей. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetIntradayCandlesResultWebResponse</returns>
        ApiResponse<GetIntradayCandlesResultWebResponse> PublicApiV1IntradayCandlesGetWithHttpInfo(string? securityBoard = default(string?), string? securityCode = default(string?), string? timeFrame = default(string?), DateOnly? intervalFrom = default(DateOnly?), DateOnly? intervalTo = default(DateOnly?), int? intervalCount = default(int?), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IIntradayCandlesApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Returns the list of intraday candles.  Возвращает внутридневные свечи.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="securityBoard">Trading Board.  Режим торгов. (optional)</param>
        /// <param name="securityCode">Security Code.  Тикер инструмента. (optional)</param>
        /// <param name="timeFrame">Timeframe.  Временной интервал. (optional)</param>
        /// <param name="intervalFrom">Date from.  Дата начала. (optional)</param>
        /// <param name="intervalTo">Date to.  Дата окончания. (optional)</param>
        /// <param name="intervalCount">Candles count limit.  Количество свечей. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetIntradayCandlesResultWebResponse</returns>
        System.Threading.Tasks.Task<GetIntradayCandlesResultWebResponse> PublicApiV1IntradayCandlesGetAsync(string? securityBoard = default(string?), string? securityCode = default(string?), string? timeFrame = default(string?), DateOnly? intervalFrom = default(DateOnly?), DateOnly? intervalTo = default(DateOnly?), int? intervalCount = default(int?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Returns the list of intraday candles.  Возвращает внутридневные свечи.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="securityBoard">Trading Board.  Режим торгов. (optional)</param>
        /// <param name="securityCode">Security Code.  Тикер инструмента. (optional)</param>
        /// <param name="timeFrame">Timeframe.  Временной интервал. (optional)</param>
        /// <param name="intervalFrom">Date from.  Дата начала. (optional)</param>
        /// <param name="intervalTo">Date to.  Дата окончания. (optional)</param>
        /// <param name="intervalCount">Candles count limit.  Количество свечей. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetIntradayCandlesResultWebResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetIntradayCandlesResultWebResponse>> PublicApiV1IntradayCandlesGetWithHttpInfoAsync(string? securityBoard = default(string?), string? securityCode = default(string?), string? timeFrame = default(string?), DateOnly? intervalFrom = default(DateOnly?), DateOnly? intervalTo = default(DateOnly?), int? intervalCount = default(int?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IIntradayCandlesApi : IIntradayCandlesApiSync, IIntradayCandlesApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class IntradayCandlesApi : IIntradayCandlesApi
    {
        private Org.OpenAPITools.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="IntradayCandlesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public IntradayCandlesApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="IntradayCandlesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public IntradayCandlesApi(string basePath)
        {
            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                new Org.OpenAPITools.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="IntradayCandlesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public IntradayCandlesApi(Org.OpenAPITools.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="IntradayCandlesApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public IntradayCandlesApi(Org.OpenAPITools.Client.ISynchronousClient client, Org.OpenAPITools.Client.IAsynchronousClient asyncClient, Org.OpenAPITools.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Org.OpenAPITools.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Org.OpenAPITools.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Org.OpenAPITools.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Org.OpenAPITools.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Returns the list of intraday candles.  Возвращает внутридневные свечи. 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="securityBoard">Trading Board.  Режим торгов. (optional)</param>
        /// <param name="securityCode">Security Code.  Тикер инструмента. (optional)</param>
        /// <param name="timeFrame">Timeframe.  Временной интервал. (optional)</param>
        /// <param name="intervalFrom">Date from.  Дата начала. (optional)</param>
        /// <param name="intervalTo">Date to.  Дата окончания. (optional)</param>
        /// <param name="intervalCount">Candles count limit.  Количество свечей. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetIntradayCandlesResultWebResponse</returns>
        public GetIntradayCandlesResultWebResponse PublicApiV1IntradayCandlesGet(string? securityBoard = default(string?), string? securityCode = default(string?), string? timeFrame = default(string?), DateOnly? intervalFrom = default(DateOnly?), DateOnly? intervalTo = default(DateOnly?), int? intervalCount = default(int?), int operationIndex = 0)
        {
            Org.OpenAPITools.Client.ApiResponse<GetIntradayCandlesResultWebResponse> localVarResponse = PublicApiV1IntradayCandlesGetWithHttpInfo(securityBoard, securityCode, timeFrame, intervalFrom, intervalTo, intervalCount);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Returns the list of intraday candles.  Возвращает внутридневные свечи. 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="securityBoard">Trading Board.  Режим торгов. (optional)</param>
        /// <param name="securityCode">Security Code.  Тикер инструмента. (optional)</param>
        /// <param name="timeFrame">Timeframe.  Временной интервал. (optional)</param>
        /// <param name="intervalFrom">Date from.  Дата начала. (optional)</param>
        /// <param name="intervalTo">Date to.  Дата окончания. (optional)</param>
        /// <param name="intervalCount">Candles count limit.  Количество свечей. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetIntradayCandlesResultWebResponse</returns>
        public Org.OpenAPITools.Client.ApiResponse<GetIntradayCandlesResultWebResponse> PublicApiV1IntradayCandlesGetWithHttpInfo(string? securityBoard = default(string?), string? securityCode = default(string?), string? timeFrame = default(string?), DateOnly? intervalFrom = default(DateOnly?), DateOnly? intervalTo = default(DateOnly?), int? intervalCount = default(int?), int operationIndex = 0)
        {
            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (securityBoard != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "SecurityBoard", securityBoard));
            }
            if (securityCode != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "SecurityCode", securityCode));
            }
            if (timeFrame != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "TimeFrame", timeFrame));
            }
            if (intervalFrom != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "Interval.From", intervalFrom));
            }
            if (intervalTo != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "Interval.To", intervalTo));
            }
            if (intervalCount != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "Interval.Count", intervalCount));
            }

            localVarRequestOptions.Operation = "IntradayCandlesApi.PublicApiV1IntradayCandlesGet";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (AccessTokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-Api-Key", this.Configuration.GetApiKeyWithPrefix("X-Api-Key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<GetIntradayCandlesResultWebResponse>("/public/api/v1/intraday-candles", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PublicApiV1IntradayCandlesGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Returns the list of intraday candles.  Возвращает внутридневные свечи. 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="securityBoard">Trading Board.  Режим торгов. (optional)</param>
        /// <param name="securityCode">Security Code.  Тикер инструмента. (optional)</param>
        /// <param name="timeFrame">Timeframe.  Временной интервал. (optional)</param>
        /// <param name="intervalFrom">Date from.  Дата начала. (optional)</param>
        /// <param name="intervalTo">Date to.  Дата окончания. (optional)</param>
        /// <param name="intervalCount">Candles count limit.  Количество свечей. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetIntradayCandlesResultWebResponse</returns>
        public async System.Threading.Tasks.Task<GetIntradayCandlesResultWebResponse> PublicApiV1IntradayCandlesGetAsync(string? securityBoard = default(string?), string? securityCode = default(string?), string? timeFrame = default(string?), DateOnly? intervalFrom = default(DateOnly?), DateOnly? intervalTo = default(DateOnly?), int? intervalCount = default(int?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<GetIntradayCandlesResultWebResponse> localVarResponse = await PublicApiV1IntradayCandlesGetWithHttpInfoAsync(securityBoard, securityCode, timeFrame, intervalFrom, intervalTo, intervalCount, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Returns the list of intraday candles.  Возвращает внутридневные свечи. 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="securityBoard">Trading Board.  Режим торгов. (optional)</param>
        /// <param name="securityCode">Security Code.  Тикер инструмента. (optional)</param>
        /// <param name="timeFrame">Timeframe.  Временной интервал. (optional)</param>
        /// <param name="intervalFrom">Date from.  Дата начала. (optional)</param>
        /// <param name="intervalTo">Date to.  Дата окончания. (optional)</param>
        /// <param name="intervalCount">Candles count limit.  Количество свечей. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetIntradayCandlesResultWebResponse)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<GetIntradayCandlesResultWebResponse>> PublicApiV1IntradayCandlesGetWithHttpInfoAsync(string? securityBoard = default(string?), string? securityCode = default(string?), string? timeFrame = default(string?), DateOnly? intervalFrom = default(DateOnly?), DateOnly? intervalTo = default(DateOnly?), int? intervalCount = default(int?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (securityBoard != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "SecurityBoard", securityBoard));
            }
            if (securityCode != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "SecurityCode", securityCode));
            }
            if (timeFrame != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "TimeFrame", timeFrame));
            }
            if (intervalFrom != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "Interval.From", intervalFrom));
            }
            if (intervalTo != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "Interval.To", intervalTo));
            }
            if (intervalCount != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "Interval.Count", intervalCount));
            }

            localVarRequestOptions.Operation = "IntradayCandlesApi.PublicApiV1IntradayCandlesGet";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (AccessTokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-Api-Key", this.Configuration.GetApiKeyWithPrefix("X-Api-Key"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<GetIntradayCandlesResultWebResponse>("/public/api/v1/intraday-candles", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PublicApiV1IntradayCandlesGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
