/*
 * Trade API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: current
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Org.OpenAPITools.Client;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPortfolioApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Returns portfolio.  Возвращает портфель.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clientId">Trade Account ID.  Идентификатор торгового счёта. (optional)</param>
        /// <param name="contentIncludeCurrencies">Currency positions.  Валютные позиции. (optional)</param>
        /// <param name="contentIncludeMoney">Money positions.  Денежные позиции. (optional)</param>
        /// <param name="contentIncludePositions">DEPO positions.  Позиции DEPO. (optional)</param>
        /// <param name="contentIncludeMaxBuySell">Buy and Sell limits.  Лимиты покупки и продажи. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetPortfolioResultWebResponse</returns>
        GetPortfolioResultWebResponse PublicApiV1PortfolioGet(string? clientId = default(string?), bool? contentIncludeCurrencies = default(bool?), bool? contentIncludeMoney = default(bool?), bool? contentIncludePositions = default(bool?), bool? contentIncludeMaxBuySell = default(bool?), int operationIndex = 0);

        /// <summary>
        /// Returns portfolio.  Возвращает портфель.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clientId">Trade Account ID.  Идентификатор торгового счёта. (optional)</param>
        /// <param name="contentIncludeCurrencies">Currency positions.  Валютные позиции. (optional)</param>
        /// <param name="contentIncludeMoney">Money positions.  Денежные позиции. (optional)</param>
        /// <param name="contentIncludePositions">DEPO positions.  Позиции DEPO. (optional)</param>
        /// <param name="contentIncludeMaxBuySell">Buy and Sell limits.  Лимиты покупки и продажи. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetPortfolioResultWebResponse</returns>
        ApiResponse<GetPortfolioResultWebResponse> PublicApiV1PortfolioGetWithHttpInfo(string? clientId = default(string?), bool? contentIncludeCurrencies = default(bool?), bool? contentIncludeMoney = default(bool?), bool? contentIncludePositions = default(bool?), bool? contentIncludeMaxBuySell = default(bool?), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPortfolioApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Returns portfolio.  Возвращает портфель.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clientId">Trade Account ID.  Идентификатор торгового счёта. (optional)</param>
        /// <param name="contentIncludeCurrencies">Currency positions.  Валютные позиции. (optional)</param>
        /// <param name="contentIncludeMoney">Money positions.  Денежные позиции. (optional)</param>
        /// <param name="contentIncludePositions">DEPO positions.  Позиции DEPO. (optional)</param>
        /// <param name="contentIncludeMaxBuySell">Buy and Sell limits.  Лимиты покупки и продажи. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetPortfolioResultWebResponse</returns>
        System.Threading.Tasks.Task<GetPortfolioResultWebResponse> PublicApiV1PortfolioGetAsync(string? clientId = default(string?), bool? contentIncludeCurrencies = default(bool?), bool? contentIncludeMoney = default(bool?), bool? contentIncludePositions = default(bool?), bool? contentIncludeMaxBuySell = default(bool?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Returns portfolio.  Возвращает портфель.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clientId">Trade Account ID.  Идентификатор торгового счёта. (optional)</param>
        /// <param name="contentIncludeCurrencies">Currency positions.  Валютные позиции. (optional)</param>
        /// <param name="contentIncludeMoney">Money positions.  Денежные позиции. (optional)</param>
        /// <param name="contentIncludePositions">DEPO positions.  Позиции DEPO. (optional)</param>
        /// <param name="contentIncludeMaxBuySell">Buy and Sell limits.  Лимиты покупки и продажи. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetPortfolioResultWebResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetPortfolioResultWebResponse>> PublicApiV1PortfolioGetWithHttpInfoAsync(string? clientId = default(string?), bool? contentIncludeCurrencies = default(bool?), bool? contentIncludeMoney = default(bool?), bool? contentIncludePositions = default(bool?), bool? contentIncludeMaxBuySell = default(bool?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPortfolioApi : IPortfolioApiSync, IPortfolioApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class PortfolioApi : IPortfolioApi
    {
        private Org.OpenAPITools.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="PortfolioApi"/> class.
        /// </summary>
        /// <returns></returns>
        public PortfolioApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PortfolioApi"/> class.
        /// </summary>
        /// <returns></returns>
        public PortfolioApi(string basePath)
        {
            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                new Org.OpenAPITools.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PortfolioApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public PortfolioApi(Org.OpenAPITools.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PortfolioApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public PortfolioApi(Org.OpenAPITools.Client.ISynchronousClient client, Org.OpenAPITools.Client.IAsynchronousClient asyncClient, Org.OpenAPITools.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Org.OpenAPITools.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Org.OpenAPITools.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Org.OpenAPITools.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Org.OpenAPITools.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Returns portfolio.  Возвращает портфель. 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clientId">Trade Account ID.  Идентификатор торгового счёта. (optional)</param>
        /// <param name="contentIncludeCurrencies">Currency positions.  Валютные позиции. (optional)</param>
        /// <param name="contentIncludeMoney">Money positions.  Денежные позиции. (optional)</param>
        /// <param name="contentIncludePositions">DEPO positions.  Позиции DEPO. (optional)</param>
        /// <param name="contentIncludeMaxBuySell">Buy and Sell limits.  Лимиты покупки и продажи. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetPortfolioResultWebResponse</returns>
        public GetPortfolioResultWebResponse PublicApiV1PortfolioGet(string? clientId = default(string?), bool? contentIncludeCurrencies = default(bool?), bool? contentIncludeMoney = default(bool?), bool? contentIncludePositions = default(bool?), bool? contentIncludeMaxBuySell = default(bool?), int operationIndex = 0)
        {
            Org.OpenAPITools.Client.ApiResponse<GetPortfolioResultWebResponse> localVarResponse = PublicApiV1PortfolioGetWithHttpInfo(clientId, contentIncludeCurrencies, contentIncludeMoney, contentIncludePositions, contentIncludeMaxBuySell);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Returns portfolio.  Возвращает портфель. 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clientId">Trade Account ID.  Идентификатор торгового счёта. (optional)</param>
        /// <param name="contentIncludeCurrencies">Currency positions.  Валютные позиции. (optional)</param>
        /// <param name="contentIncludeMoney">Money positions.  Денежные позиции. (optional)</param>
        /// <param name="contentIncludePositions">DEPO positions.  Позиции DEPO. (optional)</param>
        /// <param name="contentIncludeMaxBuySell">Buy and Sell limits.  Лимиты покупки и продажи. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetPortfolioResultWebResponse</returns>
        public Org.OpenAPITools.Client.ApiResponse<GetPortfolioResultWebResponse> PublicApiV1PortfolioGetWithHttpInfo(string? clientId = default(string?), bool? contentIncludeCurrencies = default(bool?), bool? contentIncludeMoney = default(bool?), bool? contentIncludePositions = default(bool?), bool? contentIncludeMaxBuySell = default(bool?), int operationIndex = 0)
        {
            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (clientId != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "ClientId", clientId));
            }
            if (contentIncludeCurrencies != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "Content.IncludeCurrencies", contentIncludeCurrencies));
            }
            if (contentIncludeMoney != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "Content.IncludeMoney", contentIncludeMoney));
            }
            if (contentIncludePositions != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "Content.IncludePositions", contentIncludePositions));
            }
            if (contentIncludeMaxBuySell != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "Content.IncludeMaxBuySell", contentIncludeMaxBuySell));
            }

            localVarRequestOptions.Operation = "PortfolioApi.PublicApiV1PortfolioGet";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (AccessTokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-Api-Key", this.Configuration.GetApiKeyWithPrefix("X-Api-Key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<GetPortfolioResultWebResponse>("/public/api/v1/portfolio", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PublicApiV1PortfolioGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Returns portfolio.  Возвращает портфель. 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clientId">Trade Account ID.  Идентификатор торгового счёта. (optional)</param>
        /// <param name="contentIncludeCurrencies">Currency positions.  Валютные позиции. (optional)</param>
        /// <param name="contentIncludeMoney">Money positions.  Денежные позиции. (optional)</param>
        /// <param name="contentIncludePositions">DEPO positions.  Позиции DEPO. (optional)</param>
        /// <param name="contentIncludeMaxBuySell">Buy and Sell limits.  Лимиты покупки и продажи. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetPortfolioResultWebResponse</returns>
        public async System.Threading.Tasks.Task<GetPortfolioResultWebResponse> PublicApiV1PortfolioGetAsync(string? clientId = default(string?), bool? contentIncludeCurrencies = default(bool?), bool? contentIncludeMoney = default(bool?), bool? contentIncludePositions = default(bool?), bool? contentIncludeMaxBuySell = default(bool?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<GetPortfolioResultWebResponse> localVarResponse = await PublicApiV1PortfolioGetWithHttpInfoAsync(clientId, contentIncludeCurrencies, contentIncludeMoney, contentIncludePositions, contentIncludeMaxBuySell, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Returns portfolio.  Возвращает портфель. 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clientId">Trade Account ID.  Идентификатор торгового счёта. (optional)</param>
        /// <param name="contentIncludeCurrencies">Currency positions.  Валютные позиции. (optional)</param>
        /// <param name="contentIncludeMoney">Money positions.  Денежные позиции. (optional)</param>
        /// <param name="contentIncludePositions">DEPO positions.  Позиции DEPO. (optional)</param>
        /// <param name="contentIncludeMaxBuySell">Buy and Sell limits.  Лимиты покупки и продажи. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetPortfolioResultWebResponse)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<GetPortfolioResultWebResponse>> PublicApiV1PortfolioGetWithHttpInfoAsync(string? clientId = default(string?), bool? contentIncludeCurrencies = default(bool?), bool? contentIncludeMoney = default(bool?), bool? contentIncludePositions = default(bool?), bool? contentIncludeMaxBuySell = default(bool?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (clientId != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "ClientId", clientId));
            }
            if (contentIncludeCurrencies != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "Content.IncludeCurrencies", contentIncludeCurrencies));
            }
            if (contentIncludeMoney != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "Content.IncludeMoney", contentIncludeMoney));
            }
            if (contentIncludePositions != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "Content.IncludePositions", contentIncludePositions));
            }
            if (contentIncludeMaxBuySell != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "Content.IncludeMaxBuySell", contentIncludeMaxBuySell));
            }

            localVarRequestOptions.Operation = "PortfolioApi.PublicApiV1PortfolioGet";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (AccessTokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-Api-Key", this.Configuration.GetApiKeyWithPrefix("X-Api-Key"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<GetPortfolioResultWebResponse>("/public/api/v1/portfolio", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PublicApiV1PortfolioGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
