/*
 * Trade API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: current
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Org.OpenAPITools.Client;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IStopsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Cancels Stop Order.  Снимает стоп-заявку.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clientId">Trade Account ID.  Идентификатор торгового счёта. (optional)</param>
        /// <param name="stopId">Stop Order Id.  Идентификатор стоп-заявки. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>CancelStopResultWebResponse</returns>
        CancelStopResultWebResponse PublicApiV1StopsDelete(string? clientId = default(string?), int? stopId = default(int?), int operationIndex = 0);

        /// <summary>
        /// Cancels Stop Order.  Снимает стоп-заявку.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clientId">Trade Account ID.  Идентификатор торгового счёта. (optional)</param>
        /// <param name="stopId">Stop Order Id.  Идентификатор стоп-заявки. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of CancelStopResultWebResponse</returns>
        ApiResponse<CancelStopResultWebResponse> PublicApiV1StopsDeleteWithHttpInfo(string? clientId = default(string?), int? stopId = default(int?), int operationIndex = 0);
        /// <summary>
        /// Returns the list of Stop Orders.  Возвращает список стоп-заявок.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clientId">Trade Account ID.  Идентификатор торгового счёта. (optional)</param>
        /// <param name="includeExecuted">Include executed stops in response.  Вернуть исполненные стоп-заявки. (optional)</param>
        /// <param name="includeCanceled">Include canceled stops in response.  Вернуть отмененные стоп-заявки. (optional)</param>
        /// <param name="includeActive">Include active stops in response.  Вернуть активные стоп-заявки. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetStopsResultWebResponse</returns>
        GetStopsResultWebResponse PublicApiV1StopsGet(string? clientId = default(string?), bool? includeExecuted = default(bool?), bool? includeCanceled = default(bool?), bool? includeActive = default(bool?), int operationIndex = 0);

        /// <summary>
        /// Returns the list of Stop Orders.  Возвращает список стоп-заявок.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clientId">Trade Account ID.  Идентификатор торгового счёта. (optional)</param>
        /// <param name="includeExecuted">Include executed stops in response.  Вернуть исполненные стоп-заявки. (optional)</param>
        /// <param name="includeCanceled">Include canceled stops in response.  Вернуть отмененные стоп-заявки. (optional)</param>
        /// <param name="includeActive">Include active stops in response.  Вернуть активные стоп-заявки. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetStopsResultWebResponse</returns>
        ApiResponse<GetStopsResultWebResponse> PublicApiV1StopsGetWithHttpInfo(string? clientId = default(string?), bool? includeExecuted = default(bool?), bool? includeCanceled = default(bool?), bool? includeActive = default(bool?), int operationIndex = 0);
        /// <summary>
        /// Creates new Stop Order.  Выставляет стоп-заявку.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="newStopRequest">The request received from the client. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>NewStopResultWebResponse</returns>
        NewStopResultWebResponse PublicApiV1StopsPost(NewStopRequest? newStopRequest = default(NewStopRequest?), int operationIndex = 0);

        /// <summary>
        /// Creates new Stop Order.  Выставляет стоп-заявку.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="newStopRequest">The request received from the client. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of NewStopResultWebResponse</returns>
        ApiResponse<NewStopResultWebResponse> PublicApiV1StopsPostWithHttpInfo(NewStopRequest? newStopRequest = default(NewStopRequest?), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IStopsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Cancels Stop Order.  Снимает стоп-заявку.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clientId">Trade Account ID.  Идентификатор торгового счёта. (optional)</param>
        /// <param name="stopId">Stop Order Id.  Идентификатор стоп-заявки. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CancelStopResultWebResponse</returns>
        System.Threading.Tasks.Task<CancelStopResultWebResponse> PublicApiV1StopsDeleteAsync(string? clientId = default(string?), int? stopId = default(int?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Cancels Stop Order.  Снимает стоп-заявку.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clientId">Trade Account ID.  Идентификатор торгового счёта. (optional)</param>
        /// <param name="stopId">Stop Order Id.  Идентификатор стоп-заявки. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CancelStopResultWebResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<CancelStopResultWebResponse>> PublicApiV1StopsDeleteWithHttpInfoAsync(string? clientId = default(string?), int? stopId = default(int?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Returns the list of Stop Orders.  Возвращает список стоп-заявок.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clientId">Trade Account ID.  Идентификатор торгового счёта. (optional)</param>
        /// <param name="includeExecuted">Include executed stops in response.  Вернуть исполненные стоп-заявки. (optional)</param>
        /// <param name="includeCanceled">Include canceled stops in response.  Вернуть отмененные стоп-заявки. (optional)</param>
        /// <param name="includeActive">Include active stops in response.  Вернуть активные стоп-заявки. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetStopsResultWebResponse</returns>
        System.Threading.Tasks.Task<GetStopsResultWebResponse> PublicApiV1StopsGetAsync(string? clientId = default(string?), bool? includeExecuted = default(bool?), bool? includeCanceled = default(bool?), bool? includeActive = default(bool?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Returns the list of Stop Orders.  Возвращает список стоп-заявок.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clientId">Trade Account ID.  Идентификатор торгового счёта. (optional)</param>
        /// <param name="includeExecuted">Include executed stops in response.  Вернуть исполненные стоп-заявки. (optional)</param>
        /// <param name="includeCanceled">Include canceled stops in response.  Вернуть отмененные стоп-заявки. (optional)</param>
        /// <param name="includeActive">Include active stops in response.  Вернуть активные стоп-заявки. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetStopsResultWebResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetStopsResultWebResponse>> PublicApiV1StopsGetWithHttpInfoAsync(string? clientId = default(string?), bool? includeExecuted = default(bool?), bool? includeCanceled = default(bool?), bool? includeActive = default(bool?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Creates new Stop Order.  Выставляет стоп-заявку.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="newStopRequest">The request received from the client. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of NewStopResultWebResponse</returns>
        System.Threading.Tasks.Task<NewStopResultWebResponse> PublicApiV1StopsPostAsync(NewStopRequest? newStopRequest = default(NewStopRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Creates new Stop Order.  Выставляет стоп-заявку.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="newStopRequest">The request received from the client. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (NewStopResultWebResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<NewStopResultWebResponse>> PublicApiV1StopsPostWithHttpInfoAsync(NewStopRequest? newStopRequest = default(NewStopRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IStopsApi : IStopsApiSync, IStopsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class StopsApi : IStopsApi
    {
        private Org.OpenAPITools.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="StopsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public StopsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="StopsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public StopsApi(string basePath)
        {
            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                new Org.OpenAPITools.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="StopsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public StopsApi(Org.OpenAPITools.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="StopsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public StopsApi(Org.OpenAPITools.Client.ISynchronousClient client, Org.OpenAPITools.Client.IAsynchronousClient asyncClient, Org.OpenAPITools.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Org.OpenAPITools.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Org.OpenAPITools.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Org.OpenAPITools.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Org.OpenAPITools.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Cancels Stop Order.  Снимает стоп-заявку. 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clientId">Trade Account ID.  Идентификатор торгового счёта. (optional)</param>
        /// <param name="stopId">Stop Order Id.  Идентификатор стоп-заявки. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>CancelStopResultWebResponse</returns>
        public CancelStopResultWebResponse PublicApiV1StopsDelete(string? clientId = default(string?), int? stopId = default(int?), int operationIndex = 0)
        {
            Org.OpenAPITools.Client.ApiResponse<CancelStopResultWebResponse> localVarResponse = PublicApiV1StopsDeleteWithHttpInfo(clientId, stopId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Cancels Stop Order.  Снимает стоп-заявку. 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clientId">Trade Account ID.  Идентификатор торгового счёта. (optional)</param>
        /// <param name="stopId">Stop Order Id.  Идентификатор стоп-заявки. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of CancelStopResultWebResponse</returns>
        public Org.OpenAPITools.Client.ApiResponse<CancelStopResultWebResponse> PublicApiV1StopsDeleteWithHttpInfo(string? clientId = default(string?), int? stopId = default(int?), int operationIndex = 0)
        {
            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (clientId != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "ClientId", clientId));
            }
            if (stopId != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "StopId", stopId));
            }

            localVarRequestOptions.Operation = "StopsApi.PublicApiV1StopsDelete";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (AccessTokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-Api-Key", this.Configuration.GetApiKeyWithPrefix("X-Api-Key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<CancelStopResultWebResponse>("/public/api/v1/stops", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PublicApiV1StopsDelete", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Cancels Stop Order.  Снимает стоп-заявку. 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clientId">Trade Account ID.  Идентификатор торгового счёта. (optional)</param>
        /// <param name="stopId">Stop Order Id.  Идентификатор стоп-заявки. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CancelStopResultWebResponse</returns>
        public async System.Threading.Tasks.Task<CancelStopResultWebResponse> PublicApiV1StopsDeleteAsync(string? clientId = default(string?), int? stopId = default(int?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<CancelStopResultWebResponse> localVarResponse = await PublicApiV1StopsDeleteWithHttpInfoAsync(clientId, stopId, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Cancels Stop Order.  Снимает стоп-заявку. 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clientId">Trade Account ID.  Идентификатор торгового счёта. (optional)</param>
        /// <param name="stopId">Stop Order Id.  Идентификатор стоп-заявки. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CancelStopResultWebResponse)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<CancelStopResultWebResponse>> PublicApiV1StopsDeleteWithHttpInfoAsync(string? clientId = default(string?), int? stopId = default(int?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (clientId != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "ClientId", clientId));
            }
            if (stopId != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "StopId", stopId));
            }

            localVarRequestOptions.Operation = "StopsApi.PublicApiV1StopsDelete";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (AccessTokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-Api-Key", this.Configuration.GetApiKeyWithPrefix("X-Api-Key"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.DeleteAsync<CancelStopResultWebResponse>("/public/api/v1/stops", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PublicApiV1StopsDelete", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Returns the list of Stop Orders.  Возвращает список стоп-заявок. 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clientId">Trade Account ID.  Идентификатор торгового счёта. (optional)</param>
        /// <param name="includeExecuted">Include executed stops in response.  Вернуть исполненные стоп-заявки. (optional)</param>
        /// <param name="includeCanceled">Include canceled stops in response.  Вернуть отмененные стоп-заявки. (optional)</param>
        /// <param name="includeActive">Include active stops in response.  Вернуть активные стоп-заявки. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetStopsResultWebResponse</returns>
        public GetStopsResultWebResponse PublicApiV1StopsGet(string? clientId = default(string?), bool? includeExecuted = default(bool?), bool? includeCanceled = default(bool?), bool? includeActive = default(bool?), int operationIndex = 0)
        {
            Org.OpenAPITools.Client.ApiResponse<GetStopsResultWebResponse> localVarResponse = PublicApiV1StopsGetWithHttpInfo(clientId, includeExecuted, includeCanceled, includeActive);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Returns the list of Stop Orders.  Возвращает список стоп-заявок. 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clientId">Trade Account ID.  Идентификатор торгового счёта. (optional)</param>
        /// <param name="includeExecuted">Include executed stops in response.  Вернуть исполненные стоп-заявки. (optional)</param>
        /// <param name="includeCanceled">Include canceled stops in response.  Вернуть отмененные стоп-заявки. (optional)</param>
        /// <param name="includeActive">Include active stops in response.  Вернуть активные стоп-заявки. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetStopsResultWebResponse</returns>
        public Org.OpenAPITools.Client.ApiResponse<GetStopsResultWebResponse> PublicApiV1StopsGetWithHttpInfo(string? clientId = default(string?), bool? includeExecuted = default(bool?), bool? includeCanceled = default(bool?), bool? includeActive = default(bool?), int operationIndex = 0)
        {
            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (clientId != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "ClientId", clientId));
            }
            if (includeExecuted != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "IncludeExecuted", includeExecuted));
            }
            if (includeCanceled != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "IncludeCanceled", includeCanceled));
            }
            if (includeActive != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "IncludeActive", includeActive));
            }

            localVarRequestOptions.Operation = "StopsApi.PublicApiV1StopsGet";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (AccessTokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-Api-Key", this.Configuration.GetApiKeyWithPrefix("X-Api-Key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<GetStopsResultWebResponse>("/public/api/v1/stops", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PublicApiV1StopsGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Returns the list of Stop Orders.  Возвращает список стоп-заявок. 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clientId">Trade Account ID.  Идентификатор торгового счёта. (optional)</param>
        /// <param name="includeExecuted">Include executed stops in response.  Вернуть исполненные стоп-заявки. (optional)</param>
        /// <param name="includeCanceled">Include canceled stops in response.  Вернуть отмененные стоп-заявки. (optional)</param>
        /// <param name="includeActive">Include active stops in response.  Вернуть активные стоп-заявки. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetStopsResultWebResponse</returns>
        public async System.Threading.Tasks.Task<GetStopsResultWebResponse> PublicApiV1StopsGetAsync(string? clientId = default(string?), bool? includeExecuted = default(bool?), bool? includeCanceled = default(bool?), bool? includeActive = default(bool?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<GetStopsResultWebResponse> localVarResponse = await PublicApiV1StopsGetWithHttpInfoAsync(clientId, includeExecuted, includeCanceled, includeActive, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Returns the list of Stop Orders.  Возвращает список стоп-заявок. 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clientId">Trade Account ID.  Идентификатор торгового счёта. (optional)</param>
        /// <param name="includeExecuted">Include executed stops in response.  Вернуть исполненные стоп-заявки. (optional)</param>
        /// <param name="includeCanceled">Include canceled stops in response.  Вернуть отмененные стоп-заявки. (optional)</param>
        /// <param name="includeActive">Include active stops in response.  Вернуть активные стоп-заявки. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetStopsResultWebResponse)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<GetStopsResultWebResponse>> PublicApiV1StopsGetWithHttpInfoAsync(string? clientId = default(string?), bool? includeExecuted = default(bool?), bool? includeCanceled = default(bool?), bool? includeActive = default(bool?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (clientId != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "ClientId", clientId));
            }
            if (includeExecuted != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "IncludeExecuted", includeExecuted));
            }
            if (includeCanceled != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "IncludeCanceled", includeCanceled));
            }
            if (includeActive != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "IncludeActive", includeActive));
            }

            localVarRequestOptions.Operation = "StopsApi.PublicApiV1StopsGet";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (AccessTokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-Api-Key", this.Configuration.GetApiKeyWithPrefix("X-Api-Key"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<GetStopsResultWebResponse>("/public/api/v1/stops", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PublicApiV1StopsGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Creates new Stop Order.  Выставляет стоп-заявку. 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="newStopRequest">The request received from the client. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>NewStopResultWebResponse</returns>
        public NewStopResultWebResponse PublicApiV1StopsPost(NewStopRequest? newStopRequest = default(NewStopRequest?), int operationIndex = 0)
        {
            Org.OpenAPITools.Client.ApiResponse<NewStopResultWebResponse> localVarResponse = PublicApiV1StopsPostWithHttpInfo(newStopRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Creates new Stop Order.  Выставляет стоп-заявку. 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="newStopRequest">The request received from the client. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of NewStopResultWebResponse</returns>
        public Org.OpenAPITools.Client.ApiResponse<NewStopResultWebResponse> PublicApiV1StopsPostWithHttpInfo(NewStopRequest? newStopRequest = default(NewStopRequest?), int operationIndex = 0)
        {
            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json-patch+json",
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = newStopRequest;

            localVarRequestOptions.Operation = "StopsApi.PublicApiV1StopsPost";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (AccessTokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-Api-Key", this.Configuration.GetApiKeyWithPrefix("X-Api-Key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<NewStopResultWebResponse>("/public/api/v1/stops", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PublicApiV1StopsPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Creates new Stop Order.  Выставляет стоп-заявку. 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="newStopRequest">The request received from the client. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of NewStopResultWebResponse</returns>
        public async System.Threading.Tasks.Task<NewStopResultWebResponse> PublicApiV1StopsPostAsync(NewStopRequest? newStopRequest = default(NewStopRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<NewStopResultWebResponse> localVarResponse = await PublicApiV1StopsPostWithHttpInfoAsync(newStopRequest, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Creates new Stop Order.  Выставляет стоп-заявку. 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="newStopRequest">The request received from the client. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (NewStopResultWebResponse)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<NewStopResultWebResponse>> PublicApiV1StopsPostWithHttpInfoAsync(NewStopRequest? newStopRequest = default(NewStopRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = newStopRequest;

            localVarRequestOptions.Operation = "StopsApi.PublicApiV1StopsPost";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (AccessTokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-Api-Key", this.Configuration.GetApiKeyWithPrefix("X-Api-Key"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<NewStopResultWebResponse>("/public/api/v1/stops", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PublicApiV1StopsPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
