/*
 * Trade API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: current
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing DayCandlesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class DayCandlesApiTests : IDisposable
    {
        private DayCandlesApi instance;

        public DayCandlesApiTests()
        {
            instance = new DayCandlesApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DayCandlesApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' DayCandlesApi
            //Assert.IsType<DayCandlesApi>(instance);
        }

        /// <summary>
        /// Test PublicApiV1DayCandlesGet
        /// </summary>
        [Fact]
        public void PublicApiV1DayCandlesGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? securityBoard = null;
            //string? securityCode = null;
            //string? timeFrame = null;
            //DateOnly? intervalFrom = null;
            //DateOnly? intervalTo = null;
            //int? intervalCount = null;
            //var response = instance.PublicApiV1DayCandlesGet(securityBoard, securityCode, timeFrame, intervalFrom, intervalTo, intervalCount);
            //Assert.IsType<GetDayCandlesResultWebResponse>(response);
        }
    }
}
