/*
 * Trade API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: current
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing OrdersApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class OrdersApiTests : IDisposable
    {
        private OrdersApi instance;

        public OrdersApiTests()
        {
            instance = new OrdersApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrdersApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' OrdersApi
            //Assert.IsType<OrdersApi>(instance);
        }

        /// <summary>
        /// Test PublicApiV1OrdersDelete
        /// </summary>
        [Fact]
        public void PublicApiV1OrdersDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? clientId = null;
            //int? transactionId = null;
            //var response = instance.PublicApiV1OrdersDelete(clientId, transactionId);
            //Assert.IsType<CancelOrderResultWebResponse>(response);
        }

        /// <summary>
        /// Test PublicApiV1OrdersGet
        /// </summary>
        [Fact]
        public void PublicApiV1OrdersGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? clientId = null;
            //bool? includeMatched = null;
            //bool? includeCanceled = null;
            //bool? includeActive = null;
            //var response = instance.PublicApiV1OrdersGet(clientId, includeMatched, includeCanceled, includeActive);
            //Assert.IsType<GetOrdersResultWebResponse>(response);
        }

        /// <summary>
        /// Test PublicApiV1OrdersPost
        /// </summary>
        [Fact]
        public void PublicApiV1OrdersPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //NewOrderRequest? newOrderRequest = null;
            //var response = instance.PublicApiV1OrdersPost(newOrderRequest);
            //Assert.IsType<NewOrderResultWebResponse>(response);
        }
    }
}
