/*
 * Trade API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: current
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing PortfolioApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class PortfolioApiTests : IDisposable
    {
        private PortfolioApi instance;

        public PortfolioApiTests()
        {
            instance = new PortfolioApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PortfolioApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' PortfolioApi
            //Assert.IsType<PortfolioApi>(instance);
        }

        /// <summary>
        /// Test PublicApiV1PortfolioGet
        /// </summary>
        [Fact]
        public void PublicApiV1PortfolioGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? clientId = null;
            //bool? contentIncludeCurrencies = null;
            //bool? contentIncludeMoney = null;
            //bool? contentIncludePositions = null;
            //bool? contentIncludeMaxBuySell = null;
            //var response = instance.PublicApiV1PortfolioGet(clientId, contentIncludeCurrencies, contentIncludeMoney, contentIncludePositions, contentIncludeMaxBuySell);
            //Assert.IsType<GetPortfolioResultWebResponse>(response);
        }
    }
}
