/*
 * Trade API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: current
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing StopsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class StopsApiTests : IDisposable
    {
        private StopsApi instance;

        public StopsApiTests()
        {
            instance = new StopsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StopsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' StopsApi
            //Assert.IsType<StopsApi>(instance);
        }

        /// <summary>
        /// Test PublicApiV1StopsDelete
        /// </summary>
        [Fact]
        public void PublicApiV1StopsDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? clientId = null;
            //int? stopId = null;
            //var response = instance.PublicApiV1StopsDelete(clientId, stopId);
            //Assert.IsType<CancelStopResultWebResponse>(response);
        }

        /// <summary>
        /// Test PublicApiV1StopsGet
        /// </summary>
        [Fact]
        public void PublicApiV1StopsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? clientId = null;
            //bool? includeExecuted = null;
            //bool? includeCanceled = null;
            //bool? includeActive = null;
            //var response = instance.PublicApiV1StopsGet(clientId, includeExecuted, includeCanceled, includeActive);
            //Assert.IsType<GetStopsResultWebResponse>(response);
        }

        /// <summary>
        /// Test PublicApiV1StopsPost
        /// </summary>
        [Fact]
        public void PublicApiV1StopsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //NewStopRequest? newStopRequest = null;
            //var response = instance.PublicApiV1StopsPost(newStopRequest);
            //Assert.IsType<NewStopResultWebResponse>(response);
        }
    }
}
