/*
 * Trade API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: current
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// GetIntradayCandlesRequest result.  Результат GetIntradayCandlesRequest.
    /// </summary>
    [DataContract(Name = "GetIntradayCandlesResult")]
    public partial class GetIntradayCandlesResult : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetIntradayCandlesResult" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        public GetIntradayCandlesResult()
        {
        }

        /// <summary>
        /// Candles list.  Список свечей.
        /// </summary>
        /// <value>Candles list.  Список свечей.</value>
        [DataMember(Name = "candles", EmitDefaultValue = true)]
        public List<IntradayCandle> Candles { get; private set; }

        /// <summary>
        /// Returns false as Candles should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeCandles()
        {
            return false;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetIntradayCandlesResult {\n");
            sb.Append("  Candles: ").Append(Candles).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
