/*
 * Trade API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: current
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CancelStopResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CancelStopResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CancelStopResult
        //private CancelStopResult instance;

        public CancelStopResultTests()
        {
            // TODO uncomment below to create an instance of CancelStopResult
            //instance = new CancelStopResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CancelStopResult
        /// </summary>
        [Fact]
        public void CancelStopResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" CancelStopResult
            //Assert.IsType<CancelStopResult>(instance);
        }

        /// <summary>
        /// Test the property 'ClientId'
        /// </summary>
        [Fact]
        public void ClientIdTest()
        {
            // TODO unit test for the property 'ClientId'
        }

        /// <summary>
        /// Test the property 'StopId'
        /// </summary>
        [Fact]
        public void StopIdTest()
        {
            // TODO unit test for the property 'StopId'
        }
    }
}
