/*
 * Trade API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: current
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CurrencyRow
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CurrencyRowTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CurrencyRow
        //private CurrencyRow instance;

        public CurrencyRowTests()
        {
            // TODO uncomment below to create an instance of CurrencyRow
            //instance = new CurrencyRow();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CurrencyRow
        /// </summary>
        [Fact]
        public void CurrencyRowInstanceTest()
        {
            // TODO uncomment below to test "IsType" CurrencyRow
            //Assert.IsType<CurrencyRow>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Balance'
        /// </summary>
        [Fact]
        public void BalanceTest()
        {
            // TODO unit test for the property 'Balance'
        }

        /// <summary>
        /// Test the property 'CrossRate'
        /// </summary>
        [Fact]
        public void CrossRateTest()
        {
            // TODO unit test for the property 'CrossRate'
        }

        /// <summary>
        /// Test the property 'Equity'
        /// </summary>
        [Fact]
        public void EquityTest()
        {
            // TODO unit test for the property 'Equity'
        }

        /// <summary>
        /// Test the property 'UnrealizedProfit'
        /// </summary>
        [Fact]
        public void UnrealizedProfitTest()
        {
            // TODO unit test for the property 'UnrealizedProfit'
        }
    }
}
