/*
 * Trade API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: current
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing DayCandle
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DayCandleTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DayCandle
        //private DayCandle instance;

        public DayCandleTests()
        {
            // TODO uncomment below to create an instance of DayCandle
            //instance = new DayCandle();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DayCandle
        /// </summary>
        [Fact]
        public void DayCandleInstanceTest()
        {
            // TODO uncomment below to test "IsType" DayCandle
            //Assert.IsType<DayCandle>(instance);
        }

        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Fact]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }

        /// <summary>
        /// Test the property 'Open'
        /// </summary>
        [Fact]
        public void OpenTest()
        {
            // TODO unit test for the property 'Open'
        }

        /// <summary>
        /// Test the property 'Close'
        /// </summary>
        [Fact]
        public void CloseTest()
        {
            // TODO unit test for the property 'Close'
        }

        /// <summary>
        /// Test the property 'High'
        /// </summary>
        [Fact]
        public void HighTest()
        {
            // TODO unit test for the property 'High'
        }

        /// <summary>
        /// Test the property 'Low'
        /// </summary>
        [Fact]
        public void LowTest()
        {
            // TODO unit test for the property 'Low'
        }

        /// <summary>
        /// Test the property 'Volume'
        /// </summary>
        [Fact]
        public void VolumeTest()
        {
            // TODO unit test for the property 'Volume'
        }
    }
}
