/*
 * Trade API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: current
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing GetIntradayCandlesResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetIntradayCandlesResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetIntradayCandlesResult
        //private GetIntradayCandlesResult instance;

        public GetIntradayCandlesResultTests()
        {
            // TODO uncomment below to create an instance of GetIntradayCandlesResult
            //instance = new GetIntradayCandlesResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetIntradayCandlesResult
        /// </summary>
        [Fact]
        public void GetIntradayCandlesResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetIntradayCandlesResult
            //Assert.IsType<GetIntradayCandlesResult>(instance);
        }

        /// <summary>
        /// Test the property 'Candles'
        /// </summary>
        [Fact]
        public void CandlesTest()
        {
            // TODO unit test for the property 'Candles'
        }
    }
}
