/*
 * Trade API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: current
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing GetOrdersResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetOrdersResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetOrdersResult
        //private GetOrdersResult instance;

        public GetOrdersResultTests()
        {
            // TODO uncomment below to create an instance of GetOrdersResult
            //instance = new GetOrdersResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetOrdersResult
        /// </summary>
        [Fact]
        public void GetOrdersResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetOrdersResult
            //Assert.IsType<GetOrdersResult>(instance);
        }

        /// <summary>
        /// Test the property 'ClientId'
        /// </summary>
        [Fact]
        public void ClientIdTest()
        {
            // TODO unit test for the property 'ClientId'
        }

        /// <summary>
        /// Test the property 'Orders'
        /// </summary>
        [Fact]
        public void OrdersTest()
        {
            // TODO unit test for the property 'Orders'
        }
    }
}
