/*
 * Trade API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: current
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing GetPortfolioResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetPortfolioResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetPortfolioResult
        //private GetPortfolioResult instance;

        public GetPortfolioResultTests()
        {
            // TODO uncomment below to create an instance of GetPortfolioResult
            //instance = new GetPortfolioResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetPortfolioResult
        /// </summary>
        [Fact]
        public void GetPortfolioResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetPortfolioResult
            //Assert.IsType<GetPortfolioResult>(instance);
        }

        /// <summary>
        /// Test the property 'ClientId'
        /// </summary>
        [Fact]
        public void ClientIdTest()
        {
            // TODO unit test for the property 'ClientId'
        }

        /// <summary>
        /// Test the property 'Content'
        /// </summary>
        [Fact]
        public void ContentTest()
        {
            // TODO unit test for the property 'Content'
        }

        /// <summary>
        /// Test the property 'Equity'
        /// </summary>
        [Fact]
        public void EquityTest()
        {
            // TODO unit test for the property 'Equity'
        }

        /// <summary>
        /// Test the property 'Balance'
        /// </summary>
        [Fact]
        public void BalanceTest()
        {
            // TODO unit test for the property 'Balance'
        }

        /// <summary>
        /// Test the property 'Positions'
        /// </summary>
        [Fact]
        public void PositionsTest()
        {
            // TODO unit test for the property 'Positions'
        }

        /// <summary>
        /// Test the property 'Currencies'
        /// </summary>
        [Fact]
        public void CurrenciesTest()
        {
            // TODO unit test for the property 'Currencies'
        }

        /// <summary>
        /// Test the property 'Money'
        /// </summary>
        [Fact]
        public void MoneyTest()
        {
            // TODO unit test for the property 'Money'
        }
    }
}
