/*
 * Trade API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: current
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing GetPortfolioResultWebResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetPortfolioResultWebResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetPortfolioResultWebResponse
        //private GetPortfolioResultWebResponse instance;

        public GetPortfolioResultWebResponseTests()
        {
            // TODO uncomment below to create an instance of GetPortfolioResultWebResponse
            //instance = new GetPortfolioResultWebResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetPortfolioResultWebResponse
        /// </summary>
        [Fact]
        public void GetPortfolioResultWebResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetPortfolioResultWebResponse
            //Assert.IsType<GetPortfolioResultWebResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
    }
}
