/*
 * Trade API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: current
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing GetSecuritiesResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetSecuritiesResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetSecuritiesResult
        //private GetSecuritiesResult instance;

        public GetSecuritiesResultTests()
        {
            // TODO uncomment below to create an instance of GetSecuritiesResult
            //instance = new GetSecuritiesResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetSecuritiesResult
        /// </summary>
        [Fact]
        public void GetSecuritiesResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetSecuritiesResult
            //Assert.IsType<GetSecuritiesResult>(instance);
        }

        /// <summary>
        /// Test the property 'Securities'
        /// </summary>
        [Fact]
        public void SecuritiesTest()
        {
            // TODO unit test for the property 'Securities'
        }
    }
}
