/*
 * Trade API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: current
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing GetStopsResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetStopsResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetStopsResult
        //private GetStopsResult instance;

        public GetStopsResultTests()
        {
            // TODO uncomment below to create an instance of GetStopsResult
            //instance = new GetStopsResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetStopsResult
        /// </summary>
        [Fact]
        public void GetStopsResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetStopsResult
            //Assert.IsType<GetStopsResult>(instance);
        }

        /// <summary>
        /// Test the property 'ClientId'
        /// </summary>
        [Fact]
        public void ClientIdTest()
        {
            // TODO unit test for the property 'ClientId'
        }

        /// <summary>
        /// Test the property 'Stops'
        /// </summary>
        [Fact]
        public void StopsTest()
        {
            // TODO unit test for the property 'Stops'
        }
    }
}
