/*
 * Trade API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: current
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Market
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MarketTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Market
        //private Market instance;

        public MarketTests()
        {
            // TODO uncomment below to create an instance of Market
            //instance = new Market();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Market
        /// </summary>
        [Fact]
        public void MarketInstanceTest()
        {
            // TODO uncomment below to test "IsType" Market
            //Assert.IsType<Market>(instance);
        }
    }
}
