/*
 * Trade API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: current
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing NewOrderResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NewOrderResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NewOrderResult
        //private NewOrderResult instance;

        public NewOrderResultTests()
        {
            // TODO uncomment below to create an instance of NewOrderResult
            //instance = new NewOrderResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NewOrderResult
        /// </summary>
        [Fact]
        public void NewOrderResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" NewOrderResult
            //Assert.IsType<NewOrderResult>(instance);
        }

        /// <summary>
        /// Test the property 'ClientId'
        /// </summary>
        [Fact]
        public void ClientIdTest()
        {
            // TODO unit test for the property 'ClientId'
        }

        /// <summary>
        /// Test the property 'TransactionId'
        /// </summary>
        [Fact]
        public void TransactionIdTest()
        {
            // TODO unit test for the property 'TransactionId'
        }

        /// <summary>
        /// Test the property 'SecurityCode'
        /// </summary>
        [Fact]
        public void SecurityCodeTest()
        {
            // TODO unit test for the property 'SecurityCode'
        }
    }
}
