/*
 * Trade API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: current
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing NewOrderRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NewOrderRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NewOrderRequest
        //private NewOrderRequest instance;

        public NewOrderRequestTests()
        {
            // TODO uncomment below to create an instance of NewOrderRequest
            //instance = new NewOrderRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NewOrderRequest
        /// </summary>
        [Fact]
        public void NewOrderRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" NewOrderRequest
            //Assert.IsType<NewOrderRequest>(instance);
        }

        /// <summary>
        /// Test the property 'ClientId'
        /// </summary>
        [Fact]
        public void ClientIdTest()
        {
            // TODO unit test for the property 'ClientId'
        }

        /// <summary>
        /// Test the property 'SecurityBoard'
        /// </summary>
        [Fact]
        public void SecurityBoardTest()
        {
            // TODO unit test for the property 'SecurityBoard'
        }

        /// <summary>
        /// Test the property 'SecurityCode'
        /// </summary>
        [Fact]
        public void SecurityCodeTest()
        {
            // TODO unit test for the property 'SecurityCode'
        }

        /// <summary>
        /// Test the property 'BuySell'
        /// </summary>
        [Fact]
        public void BuySellTest()
        {
            // TODO unit test for the property 'BuySell'
        }

        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Fact]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }

        /// <summary>
        /// Test the property 'UseCredit'
        /// </summary>
        [Fact]
        public void UseCreditTest()
        {
            // TODO unit test for the property 'UseCredit'
        }

        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Fact]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }

        /// <summary>
        /// Test the property 'Property'
        /// </summary>
        [Fact]
        public void PropertyTest()
        {
            // TODO unit test for the property 'Property'
        }

        /// <summary>
        /// Test the property 'Condition'
        /// </summary>
        [Fact]
        public void ConditionTest()
        {
            // TODO unit test for the property 'Condition'
        }

        /// <summary>
        /// Test the property 'ValidBefore'
        /// </summary>
        [Fact]
        public void ValidBeforeTest()
        {
            // TODO unit test for the property 'ValidBefore'
        }
    }
}
