/*
 * Trade API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: current
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing NewStopResultWebResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NewStopResultWebResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NewStopResultWebResponse
        //private NewStopResultWebResponse instance;

        public NewStopResultWebResponseTests()
        {
            // TODO uncomment below to create an instance of NewStopResultWebResponse
            //instance = new NewStopResultWebResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NewStopResultWebResponse
        /// </summary>
        [Fact]
        public void NewStopResultWebResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" NewStopResultWebResponse
            //Assert.IsType<NewStopResultWebResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
    }
}
