/*
 * Trade API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: current
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing NewStopRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NewStopRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NewStopRequest
        //private NewStopRequest instance;

        public NewStopRequestTests()
        {
            // TODO uncomment below to create an instance of NewStopRequest
            //instance = new NewStopRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NewStopRequest
        /// </summary>
        [Fact]
        public void NewStopRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" NewStopRequest
            //Assert.IsType<NewStopRequest>(instance);
        }

        /// <summary>
        /// Test the property 'ClientId'
        /// </summary>
        [Fact]
        public void ClientIdTest()
        {
            // TODO unit test for the property 'ClientId'
        }

        /// <summary>
        /// Test the property 'SecurityBoard'
        /// </summary>
        [Fact]
        public void SecurityBoardTest()
        {
            // TODO unit test for the property 'SecurityBoard'
        }

        /// <summary>
        /// Test the property 'SecurityCode'
        /// </summary>
        [Fact]
        public void SecurityCodeTest()
        {
            // TODO unit test for the property 'SecurityCode'
        }

        /// <summary>
        /// Test the property 'BuySell'
        /// </summary>
        [Fact]
        public void BuySellTest()
        {
            // TODO unit test for the property 'BuySell'
        }

        /// <summary>
        /// Test the property 'StopLoss'
        /// </summary>
        [Fact]
        public void StopLossTest()
        {
            // TODO unit test for the property 'StopLoss'
        }

        /// <summary>
        /// Test the property 'TakeProfit'
        /// </summary>
        [Fact]
        public void TakeProfitTest()
        {
            // TODO unit test for the property 'TakeProfit'
        }

        /// <summary>
        /// Test the property 'ExpirationDate'
        /// </summary>
        [Fact]
        public void ExpirationDateTest()
        {
            // TODO unit test for the property 'ExpirationDate'
        }

        /// <summary>
        /// Test the property 'LinkOrder'
        /// </summary>
        [Fact]
        public void LinkOrderTest()
        {
            // TODO unit test for the property 'LinkOrder'
        }

        /// <summary>
        /// Test the property 'ValidBefore'
        /// </summary>
        [Fact]
        public void ValidBeforeTest()
        {
            // TODO unit test for the property 'ValidBefore'
        }
    }
}
