/*
 * Trade API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: current
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing NewStopResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NewStopResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NewStopResult
        //private NewStopResult instance;

        public NewStopResultTests()
        {
            // TODO uncomment below to create an instance of NewStopResult
            //instance = new NewStopResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NewStopResult
        /// </summary>
        [Fact]
        public void NewStopResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" NewStopResult
            //Assert.IsType<NewStopResult>(instance);
        }

        /// <summary>
        /// Test the property 'ClientId'
        /// </summary>
        [Fact]
        public void ClientIdTest()
        {
            // TODO unit test for the property 'ClientId'
        }

        /// <summary>
        /// Test the property 'StopId'
        /// </summary>
        [Fact]
        public void StopIdTest()
        {
            // TODO unit test for the property 'StopId'
        }

        /// <summary>
        /// Test the property 'SecurityCode'
        /// </summary>
        [Fact]
        public void SecurityCodeTest()
        {
            // TODO unit test for the property 'SecurityCode'
        }

        /// <summary>
        /// Test the property 'SecurityBoard'
        /// </summary>
        [Fact]
        public void SecurityBoardTest()
        {
            // TODO unit test for the property 'SecurityBoard'
        }
    }
}
