/*
 * Trade API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: current
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing OrderConditionType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderConditionTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderConditionType
        //private OrderConditionType instance;

        public OrderConditionTypeTests()
        {
            // TODO uncomment below to create an instance of OrderConditionType
            //instance = new OrderConditionType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderConditionType
        /// </summary>
        [Fact]
        public void OrderConditionTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderConditionType
            //Assert.IsType<OrderConditionType>(instance);
        }
    }
}
