/*
 * Trade API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: current
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing OrderProperty
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderPropertyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderProperty
        //private OrderProperty instance;

        public OrderPropertyTests()
        {
            // TODO uncomment below to create an instance of OrderProperty
            //instance = new OrderProperty();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderProperty
        /// </summary>
        [Fact]
        public void OrderPropertyInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderProperty
            //Assert.IsType<OrderProperty>(instance);
        }
    }
}
