/*
 * Trade API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: current
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing PortfolioContent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PortfolioContentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PortfolioContent
        //private PortfolioContent instance;

        public PortfolioContentTests()
        {
            // TODO uncomment below to create an instance of PortfolioContent
            //instance = new PortfolioContent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PortfolioContent
        /// </summary>
        [Fact]
        public void PortfolioContentInstanceTest()
        {
            // TODO uncomment below to test "IsType" PortfolioContent
            //Assert.IsType<PortfolioContent>(instance);
        }

        /// <summary>
        /// Test the property 'IncludeCurrencies'
        /// </summary>
        [Fact]
        public void IncludeCurrenciesTest()
        {
            // TODO unit test for the property 'IncludeCurrencies'
        }

        /// <summary>
        /// Test the property 'IncludeMoney'
        /// </summary>
        [Fact]
        public void IncludeMoneyTest()
        {
            // TODO unit test for the property 'IncludeMoney'
        }

        /// <summary>
        /// Test the property 'IncludePositions'
        /// </summary>
        [Fact]
        public void IncludePositionsTest()
        {
            // TODO unit test for the property 'IncludePositions'
        }

        /// <summary>
        /// Test the property 'IncludeMaxBuySell'
        /// </summary>
        [Fact]
        public void IncludeMaxBuySellTest()
        {
            // TODO unit test for the property 'IncludeMaxBuySell'
        }
    }
}
