/*
 * Trade API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: current
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing PositionRow
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PositionRowTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PositionRow
        //private PositionRow instance;

        public PositionRowTests()
        {
            // TODO uncomment below to create an instance of PositionRow
            //instance = new PositionRow();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PositionRow
        /// </summary>
        [Fact]
        public void PositionRowInstanceTest()
        {
            // TODO uncomment below to test "IsType" PositionRow
            //Assert.IsType<PositionRow>(instance);
        }

        /// <summary>
        /// Test the property 'SecurityCode'
        /// </summary>
        [Fact]
        public void SecurityCodeTest()
        {
            // TODO unit test for the property 'SecurityCode'
        }

        /// <summary>
        /// Test the property 'Market'
        /// </summary>
        [Fact]
        public void MarketTest()
        {
            // TODO unit test for the property 'Market'
        }

        /// <summary>
        /// Test the property 'Balance'
        /// </summary>
        [Fact]
        public void BalanceTest()
        {
            // TODO unit test for the property 'Balance'
        }

        /// <summary>
        /// Test the property 'CurrentPrice'
        /// </summary>
        [Fact]
        public void CurrentPriceTest()
        {
            // TODO unit test for the property 'CurrentPrice'
        }

        /// <summary>
        /// Test the property 'Equity'
        /// </summary>
        [Fact]
        public void EquityTest()
        {
            // TODO unit test for the property 'Equity'
        }

        /// <summary>
        /// Test the property 'AveragePrice'
        /// </summary>
        [Fact]
        public void AveragePriceTest()
        {
            // TODO unit test for the property 'AveragePrice'
        }

        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }

        /// <summary>
        /// Test the property 'AccumulatedProfit'
        /// </summary>
        [Fact]
        public void AccumulatedProfitTest()
        {
            // TODO unit test for the property 'AccumulatedProfit'
        }

        /// <summary>
        /// Test the property 'TodayProfit'
        /// </summary>
        [Fact]
        public void TodayProfitTest()
        {
            // TODO unit test for the property 'TodayProfit'
        }

        /// <summary>
        /// Test the property 'UnrealizedProfit'
        /// </summary>
        [Fact]
        public void UnrealizedProfitTest()
        {
            // TODO unit test for the property 'UnrealizedProfit'
        }

        /// <summary>
        /// Test the property 'Profit'
        /// </summary>
        [Fact]
        public void ProfitTest()
        {
            // TODO unit test for the property 'Profit'
        }

        /// <summary>
        /// Test the property 'MaxBuy'
        /// </summary>
        [Fact]
        public void MaxBuyTest()
        {
            // TODO unit test for the property 'MaxBuy'
        }

        /// <summary>
        /// Test the property 'MaxSell'
        /// </summary>
        [Fact]
        public void MaxSellTest()
        {
            // TODO unit test for the property 'MaxSell'
        }

        /// <summary>
        /// Test the property 'PriceCurrency'
        /// </summary>
        [Fact]
        public void PriceCurrencyTest()
        {
            // TODO unit test for the property 'PriceCurrency'
        }

        /// <summary>
        /// Test the property 'AveragePriceCurrency'
        /// </summary>
        [Fact]
        public void AveragePriceCurrencyTest()
        {
            // TODO unit test for the property 'AveragePriceCurrency'
        }

        /// <summary>
        /// Test the property 'AverageRate'
        /// </summary>
        [Fact]
        public void AverageRateTest()
        {
            // TODO unit test for the property 'AverageRate'
        }
    }
}
