/*
 * Trade API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: current
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Security
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SecurityTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Security
        //private Security instance;

        public SecurityTests()
        {
            // TODO uncomment below to create an instance of Security
            //instance = new Security();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Security
        /// </summary>
        [Fact]
        public void SecurityInstanceTest()
        {
            // TODO uncomment below to test "IsType" Security
            //Assert.IsType<Security>(instance);
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Board'
        /// </summary>
        [Fact]
        public void BoardTest()
        {
            // TODO unit test for the property 'Board'
        }

        /// <summary>
        /// Test the property 'Market'
        /// </summary>
        [Fact]
        public void MarketTest()
        {
            // TODO unit test for the property 'Market'
        }

        /// <summary>
        /// Test the property 'Decimals'
        /// </summary>
        [Fact]
        public void DecimalsTest()
        {
            // TODO unit test for the property 'Decimals'
        }

        /// <summary>
        /// Test the property 'LotSize'
        /// </summary>
        [Fact]
        public void LotSizeTest()
        {
            // TODO unit test for the property 'LotSize'
        }

        /// <summary>
        /// Test the property 'MinStep'
        /// </summary>
        [Fact]
        public void MinStepTest()
        {
            // TODO unit test for the property 'MinStep'
        }

        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }

        /// <summary>
        /// Test the property 'ShortName'
        /// </summary>
        [Fact]
        public void ShortNameTest()
        {
            // TODO unit test for the property 'ShortName'
        }

        /// <summary>
        /// Test the property 'Properties'
        /// </summary>
        [Fact]
        public void PropertiesTest()
        {
            // TODO unit test for the property 'Properties'
        }

        /// <summary>
        /// Test the property 'TimeZoneName'
        /// </summary>
        [Fact]
        public void TimeZoneNameTest()
        {
            // TODO unit test for the property 'TimeZoneName'
        }

        /// <summary>
        /// Test the property 'BpCost'
        /// </summary>
        [Fact]
        public void BpCostTest()
        {
            // TODO unit test for the property 'BpCost'
        }

        /// <summary>
        /// Test the property 'AccruedInterest'
        /// </summary>
        [Fact]
        public void AccruedInterestTest()
        {
            // TODO unit test for the property 'AccruedInterest'
        }

        /// <summary>
        /// Test the property 'PriceSign'
        /// </summary>
        [Fact]
        public void PriceSignTest()
        {
            // TODO unit test for the property 'PriceSign'
        }

        /// <summary>
        /// Test the property 'Ticker'
        /// </summary>
        [Fact]
        public void TickerTest()
        {
            // TODO unit test for the property 'Ticker'
        }

        /// <summary>
        /// Test the property 'LotDivider'
        /// </summary>
        [Fact]
        public void LotDividerTest()
        {
            // TODO unit test for the property 'LotDivider'
        }
    }
}
