/*
 * Trade API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: current
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing StopQuantityUnits
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StopQuantityUnitsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StopQuantityUnits
        //private StopQuantityUnits instance;

        public StopQuantityUnitsTests()
        {
            // TODO uncomment below to create an instance of StopQuantityUnits
            //instance = new StopQuantityUnits();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StopQuantityUnits
        /// </summary>
        [Fact]
        public void StopQuantityUnitsInstanceTest()
        {
            // TODO uncomment below to test "IsType" StopQuantityUnits
            //Assert.IsType<StopQuantityUnits>(instance);
        }
    }
}
