/*
 * Trade API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: current
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Stop
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StopTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Stop
        //private Stop instance;

        public StopTests()
        {
            // TODO uncomment below to create an instance of Stop
            //instance = new Stop();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Stop
        /// </summary>
        [Fact]
        public void StopInstanceTest()
        {
            // TODO uncomment below to test "IsType" Stop
            //Assert.IsType<Stop>(instance);
        }

        /// <summary>
        /// Test the property 'StopId'
        /// </summary>
        [Fact]
        public void StopIdTest()
        {
            // TODO unit test for the property 'StopId'
        }

        /// <summary>
        /// Test the property 'SecurityCode'
        /// </summary>
        [Fact]
        public void SecurityCodeTest()
        {
            // TODO unit test for the property 'SecurityCode'
        }

        /// <summary>
        /// Test the property 'SecurityBoard'
        /// </summary>
        [Fact]
        public void SecurityBoardTest()
        {
            // TODO unit test for the property 'SecurityBoard'
        }

        /// <summary>
        /// Test the property 'Market'
        /// </summary>
        [Fact]
        public void MarketTest()
        {
            // TODO unit test for the property 'Market'
        }

        /// <summary>
        /// Test the property 'ClientId'
        /// </summary>
        [Fact]
        public void ClientIdTest()
        {
            // TODO unit test for the property 'ClientId'
        }

        /// <summary>
        /// Test the property 'BuySell'
        /// </summary>
        [Fact]
        public void BuySellTest()
        {
            // TODO unit test for the property 'BuySell'
        }

        /// <summary>
        /// Test the property 'ExpirationDate'
        /// </summary>
        [Fact]
        public void ExpirationDateTest()
        {
            // TODO unit test for the property 'ExpirationDate'
        }

        /// <summary>
        /// Test the property 'LinkOrder'
        /// </summary>
        [Fact]
        public void LinkOrderTest()
        {
            // TODO unit test for the property 'LinkOrder'
        }

        /// <summary>
        /// Test the property 'ValidBefore'
        /// </summary>
        [Fact]
        public void ValidBeforeTest()
        {
            // TODO unit test for the property 'ValidBefore'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

        /// <summary>
        /// Test the property 'OrderNo'
        /// </summary>
        [Fact]
        public void OrderNoTest()
        {
            // TODO unit test for the property 'OrderNo'
        }

        /// <summary>
        /// Test the property 'TradeNo'
        /// </summary>
        [Fact]
        public void TradeNoTest()
        {
            // TODO unit test for the property 'TradeNo'
        }

        /// <summary>
        /// Test the property 'AcceptedAt'
        /// </summary>
        [Fact]
        public void AcceptedAtTest()
        {
            // TODO unit test for the property 'AcceptedAt'
        }

        /// <summary>
        /// Test the property 'CanceledAt'
        /// </summary>
        [Fact]
        public void CanceledAtTest()
        {
            // TODO unit test for the property 'CanceledAt'
        }

        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }

        /// <summary>
        /// Test the property 'TakeProfitExtremum'
        /// </summary>
        [Fact]
        public void TakeProfitExtremumTest()
        {
            // TODO unit test for the property 'TakeProfitExtremum'
        }

        /// <summary>
        /// Test the property 'TakeProfitLevel'
        /// </summary>
        [Fact]
        public void TakeProfitLevelTest()
        {
            // TODO unit test for the property 'TakeProfitLevel'
        }

        /// <summary>
        /// Test the property 'StopLoss'
        /// </summary>
        [Fact]
        public void StopLossTest()
        {
            // TODO unit test for the property 'StopLoss'
        }

        /// <summary>
        /// Test the property 'TakeProfit'
        /// </summary>
        [Fact]
        public void TakeProfitTest()
        {
            // TODO unit test for the property 'TakeProfit'
        }
    }
}
