/*
 * Trade API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: current
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing TakeProfit
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TakeProfitTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TakeProfit
        //private TakeProfit instance;

        public TakeProfitTests()
        {
            // TODO uncomment below to create an instance of TakeProfit
            //instance = new TakeProfit();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TakeProfit
        /// </summary>
        [Fact]
        public void TakeProfitInstanceTest()
        {
            // TODO uncomment below to test "IsType" TakeProfit
            //Assert.IsType<TakeProfit>(instance);
        }

        /// <summary>
        /// Test the property 'ActivationPrice'
        /// </summary>
        [Fact]
        public void ActivationPriceTest()
        {
            // TODO unit test for the property 'ActivationPrice'
        }

        /// <summary>
        /// Test the property 'CorrectionPrice'
        /// </summary>
        [Fact]
        public void CorrectionPriceTest()
        {
            // TODO unit test for the property 'CorrectionPrice'
        }

        /// <summary>
        /// Test the property 'SpreadPrice'
        /// </summary>
        [Fact]
        public void SpreadPriceTest()
        {
            // TODO unit test for the property 'SpreadPrice'
        }

        /// <summary>
        /// Test the property 'MarketPrice'
        /// </summary>
        [Fact]
        public void MarketPriceTest()
        {
            // TODO unit test for the property 'MarketPrice'
        }

        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Fact]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }

        /// <summary>
        /// Test the property 'Time'
        /// </summary>
        [Fact]
        public void TimeTest()
        {
            // TODO unit test for the property 'Time'
        }

        /// <summary>
        /// Test the property 'UseCredit'
        /// </summary>
        [Fact]
        public void UseCreditTest()
        {
            // TODO unit test for the property 'UseCredit'
        }
    }
}
